name: Create and publish a Docker images

on:
  push:
    branches: ["latest"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - context: ./zsh
            dockerfile: Dockerfile-alpine
            image: ghcr.io/essembeh/alpine
            tag: latest
          - context: ./zsh
            dockerfile: Dockerfile-debian
            image: ghcr.io/essembeh/debian
            tag: latest
          - context: ./borgmatic
            dockerfile: Dockerfile
            image: ghcr.io/essembeh/borgmatic
            tag: latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          tags: ${{ matrix.image }}:${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
